### ISSUE TITLE
when I run commond "python commander.py apps\de.k3b.android.androFotoFinder.apk",it trows exception. The python environment is python37 

### ISSUE THREAD

**Issue by androidAppGuard** [mate-android-testing/mate-commander#1]
Traceback (most recent call last):
  File "commander.py", line 52, in <module>
    class Commander:
  File "commander.py", line 134, in Commander
    def run_popen(self, cmd: list[str], use_shell: bool = True):
TypeError: 'type' object is not subscriptable

**Comment by androidAppGuard** [comment]
The problem is fixed when I update the python version from 3.6 to 3.9! But it still throw an exception when I run “python commander.py apps\de.k3b.android.androFotoFinder.apk”.  and the log is as follows:

```
Using Emulator
Emulator logging enabled. Logging to log/emu.log and log/emu_err.log
Starting Emulator...
Traceback (most recent call last):
  File "D:\tmp\mate-commander\commander.py", line 532, in <module>
    com.run_emulator()
  File "D:\tmp\mate-commander\commander.py", line 182, in run_emulator
    self.emu_proc = self.run_popen(self.emu_command, False)
  File "D:\tmp\mate-commander\commander.py", line 138, in run_popen
    return subprocess.Popen(cmd, stdout=self.f, stderr=self.f_err, shell=s)
  File "D:\soft\Anaconda\envs\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\soft\Anaconda\envs\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] 拒绝访问。
```
I try to added a "winpty" before the command to be executed in some places, then the syntax in commander.py was wrong, so I don’t know where to add the "winpty" and how to resolve this issue. 
If you have time to help answer them, I would be extremely grateful!
